pipeline {
    agent any
    
    environment {
        registry = "vinothg2309/suggestion-service"
        registryCredential = 'dockerhub'
        dockerImage = ''
        mavenHome=''
        mavenCMD=''
    }
   
    
    stages {
       
        stage('Env print'){
            steps{
                 sh label: '', 
                script: """
                    echo $env.registry .
                """
            }
        }
        stage('Git Checkout'){
            steps{
                git branch: 'master', url: 'https://github.com/vinothg2309/kubernetes.git'
            }
        }
        
        stage('mvn build'){
            steps{
                 dir('suggestion-service') {
                     script{
                        mavenHome =  tool name: 'Maven', type: 'maven'
                        mavenCMD = "${mavenHome}/bin/mvn clean package"
                        sh "${mavenCMD}"
                     }
                }
                
            }
        }
        
        stage('Docker build'){
            steps{
                dir('suggestion-service') {
                    sh label: '', 
                    script: """
                        docker build -t $env.registry .
                    """
                }
            }
        }
        
        stage('Docker Push'){
            steps{
                dir('suggestion-service') {
                    withCredentials([string(credentialsId: 'dockerhub_pwd', variable: 'DOCKER_HUB_PWD')]) {
                        sh label: '', 
                    script: """
                        docker push $env.registry
                    """
                    }
                }
            }
        }
        
        stage('Kubernetes delete'){
            steps{
                dir('suggestion-service') {
                    sh label: '', 
                    script: """
                        kubectl delete -f suggestion-service-k8s.yaml
                    """
                }
            }
        }
        
        stage('Kubernetes create'){
            steps{
                dir('suggestion-service') {
                    sh label: '', 
                    script: """
                        kubectl create -f suggestion-service-k8s.yaml
                    """
                }
            }
        }
    }
}
